"""Loop183 Multi-Scale HGConv-Region with strong regularization research lineage.

Loop183 = Loop182 多尺度 HGConv 架构 + 强正则化组合：
- weight_decay: 1e-2 → 3e-2
- dropout: 0.1 → 0.2
- max_epochs: 12 → 20
- 训练时数据增强：Mixup α=0.4, Region dropout p=0.3, Label smoothing ε=0.05
- 模型选择标准：F1-based（避免 loss-based 过早停止）
"""

from .contracts import (
    B0_FEATURE_DIM,
    BUCKET_COUNT,
    DROPOUT,
    EXPECTED_REGION_BYTES,
    EXPECTED_REGIONS,
    HGCONV_BLOCKS,
    HGCONV_FILTER_LENGTH,
    LABEL_SMOOTHING_EPS,
    LOOP_ID,
    MIXUP_ALPHA,
    MODEL_DIM,
    MULTI_SCALE_FILTER_LENGTHS,
    NUMERIC_TOLERANCE,
    PADDING_TOKEN,
    PATCH_SEQUENCE_LENGTH,
    PATCH_SIZE,
    PHASE0_SOURCE_WHITELIST,
    PHASE_A_GATE,
    PHASE_B_GATE,
    REGION_DROPOUT_PROB,
    REGION_TYPE_COUNT,
    TRANSFORMER_FFN_DIM,
    TRANSFORMER_HEADS,
    TRANSFORMER_LAYERS,
    VOCABULARY_SIZE,
    NumericTolerance,
    PhaseAResourceGate,
    PhaseBGate,
    assert_contract_invariants,
)
from .data_adapter import (
    CANONICAL_B0_CACHE_RELATIVE_PATH,
    CANONICAL_FOLD_MANIFEST_RELATIVE_PATH,
    CANONICAL_FOLD_MANIFEST_SHA256,
    CANONICAL_REGION_CACHE_RELATIVE_PATH,
    CANONICAL_REGION_CACHE_SHA256,
    FULL_TRAIN_ROWS,
    FoldSplit,
    PHASE_A_FIT_FOLDS,
    PHASE_A_FOLD_SPLIT,
    PHASE_A_FORBIDDEN_FOLDS,
    PHASE_A_SELECTION_FOLD,
    PhaseADataLoader,
    ROWS_PER_FOLD,
    RegionBatch,
    make_synthetic_batch,
    validate_b0_features_shape,
    validate_metadata_ranges,
    validate_metadata_shape,
    validate_region_tokens_shape,
    validate_token_ranges,
)
from .hgconv import (
    HGConvBlock,
    HGConvConfig,
    MultiScaleHGConvBlock,
    MultiScaleHGConvConfig,
    approximate_inverse,
    circular_convolution,
    malware_kernel_precondition,
)
from .model import HGConvRegionConfig, HGConvRegionNet, parameter_count
from .resource_cell import (
    IntegrityGateResult,
    ResourceCell,
    ResourceSample,
    ResourceViolation,
    assert_bitwise_deterministic,
    assert_budget_invariants,
    check_integrity,
)
from .source_closure import (
    ClosureReport,
    ClosureViolation,
    assert_phase0_closure,
    build_current_manifest,
    scan_source_closure,
)

__all__ = [
    # contracts
    "B0_FEATURE_DIM",
    "BUCKET_COUNT",
    "DROPOUT",
    "EXPECTED_REGION_BYTES",
    "EXPECTED_REGIONS",
    "HGCONV_BLOCKS",
    "HGCONV_FILTER_LENGTH",
    "LABEL_SMOOTHING_EPS",
    "LOOP_ID",
    "MIXUP_ALPHA",
    "MODEL_DIM",
    "MULTI_SCALE_FILTER_LENGTHS",
    "NUMERIC_TOLERANCE",
    "PADDING_TOKEN",
    "PATCH_SEQUENCE_LENGTH",
    "PATCH_SIZE",
    "PHASE0_SOURCE_WHITELIST",
    "PHASE_A_GATE",
    "PHASE_B_GATE",
    "REGION_DROPOUT_PROB",
    "REGION_TYPE_COUNT",
    "TRANSFORMER_FFN_DIM",
    "TRANSFORMER_HEADS",
    "TRANSFORMER_LAYERS",
    "VOCABULARY_SIZE",
    "NumericTolerance",
    "PhaseAResourceGate",
    "PhaseBGate",
    "assert_contract_invariants",
    # data_adapter
    "CANONICAL_B0_CACHE_RELATIVE_PATH",
    "CANONICAL_FOLD_MANIFEST_RELATIVE_PATH",
    "CANONICAL_FOLD_MANIFEST_SHA256",
    "CANONICAL_REGION_CACHE_RELATIVE_PATH",
    "CANONICAL_REGION_CACHE_SHA256",
    "FULL_TRAIN_ROWS",
    "FoldSplit",
    "PHASE_A_FIT_FOLDS",
    "PHASE_A_FOLD_SPLIT",
    "PHASE_A_FORBIDDEN_FOLDS",
    "PHASE_A_SELECTION_FOLD",
    "PhaseADataLoader",
    "ROWS_PER_FOLD",
    "RegionBatch",
    "make_synthetic_batch",
    "validate_b0_features_shape",
    "validate_metadata_ranges",
    "validate_metadata_shape",
    "validate_region_tokens_shape",
    "validate_token_ranges",
    # hgconv
    "HGConvBlock",
    "HGConvConfig",
    "MultiScaleHGConvBlock",
    "MultiScaleHGConvConfig",
    "approximate_inverse",
    "circular_convolution",
    "malware_kernel_precondition",
    # model
    "HGConvRegionConfig",
    "HGConvRegionNet",
    "parameter_count",
    # resource_cell
    "IntegrityGateResult",
    "ResourceCell",
    "ResourceSample",
    "ResourceViolation",
    "assert_bitwise_deterministic",
    "assert_budget_invariants",
    "check_integrity",
    # source_closure
    "ClosureReport",
    "ClosureViolation",
    "assert_phase0_closure",
    "build_current_manifest",
    "scan_source_closure",
]
