#!/usr/bin/env python3
"""Materialize a selected 20w raw split into a dedicated hardlink worktree.

The goal is to make the selected 200000 raw PE samples available under a clean
data root without copying payloads. The script:

- reads the source split CSV generated by build_random_20w_split.py
- creates hard links under a new worktree root, preserving relative paths
- writes a rewritten split CSV whose source_path values point at the worktree
- writes a summary JSON for auditability

It does not delete source files, rebuild cache, or train models.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import shutil
from collections import Counter
from concurrent.futures import FIRST_COMPLETED, ThreadPoolExecutor, wait
from pathlib import Path
from typing import Optional, Sequence


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE_DATA_DIR = PROJECT_ROOT / "data"
DEFAULT_WORKTREE_ROOT = PROJECT_ROOT / "data" / "random_20w_worktree"
DEFAULT_WORKTREE_SPLIT = PROJECT_ROOT / "reports" / "random_20w_split" / "random_20w_split_worktree.csv"
DEFAULT_SUMMARY_JSON = PROJECT_ROOT / "reports" / "random_20w_split" / "random_20w_worktree_summary.json"
DEFAULT_PENDING_MULTIPLIER = 4
MAX_PENDING_TASKS = 256
MAX_FAILURE_EXAMPLES = 20


def resolve_path(path: Path) -> Path:
    return path if path.is_absolute() else PROJECT_ROOT / path


def iter_rows(path: Path):
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        yield from csv.DictReader(f)


def _file_sha256(path: Path, chunk_size: int = 1024 * 1024) -> str:
    import hashlib

    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(chunk_size), b""):
            digest.update(chunk)
    return digest.hexdigest()


def safe_relative_path(source_path: Path, source_root: Path) -> Path:
    try:
        return source_path.relative_to(source_root)
    except ValueError as exc:
        source_text = str(source_path).replace("/", "\\")
        root_text = str(source_root).replace("/", "\\").rstrip("\\")
        prefix = root_text + "\\"
        if source_text.casefold().startswith(prefix.casefold()):
            return Path(source_text[len(prefix):])
        raise ValueError(f"Source path is outside source data root: {source_path}") from exc


def ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def link_or_verify(source: Path, destination: Path, *, mode: str) -> str:
    if destination.exists():
        if destination.is_file():
            try:
                if os.path.samefile(source, destination):
                    return "exists"
            except OSError:
                pass
        if (
            destination.is_file()
            and destination.stat().st_size == source.stat().st_size
            and _file_sha256(destination) == _file_sha256(source)
        ):
            return "exists"
        raise FileExistsError(f"Destination already exists with a different payload: {destination}")

    ensure_parent(destination)
    if mode == "copy":
        shutil.copy2(source, destination)
        return "copied"

    if mode != "hardlink":
        raise ValueError(f"Unsupported link mode: {mode}")

    try:
        os.link(source, destination)
        return "linked"
    except OSError as exc:
        raise OSError(f"Failed to hardlink {source} -> {destination}: {exc}") from exc


def _materialize_one(payload: tuple[int, dict, str, str, str]) -> dict:
    index, row, original_path_text, destination_text, link_mode = payload
    original_path = Path(original_path_text)
    destination = Path(destination_text)
    try:
        status = link_or_verify(original_path, destination, mode=link_mode)
        rewritten = dict(row)
        rewritten["original_source_path"] = str(original_path)
        rewritten["source_path"] = str(destination)
        return {
            "index": index,
            "failed": False,
            "status": status,
            "row": rewritten,
            "original_source_path": str(original_path),
            "materialized_source_path": str(destination),
        }
    except Exception as exc:
        return {
            "index": index,
            "failed": True,
            "status": "failed",
            "error_type": type(exc).__name__,
            "error": str(exc),
            "row": dict(row),
            "original_source_path": str(original_path),
            "materialized_source_path": str(destination),
        }


def _worker_exception_result(payload: tuple[int, dict, str, str, str], exc: BaseException) -> dict:
    index, row, original_path_text, destination_text, _link_mode = payload
    return {
        "index": index,
        "failed": True,
        "status": "failed",
        "error_type": type(exc).__name__,
        "error": str(exc),
        "row": dict(row),
        "original_source_path": str(original_path_text),
        "materialized_source_path": str(destination_text),
    }


def _record_result(
    result: dict,
    writer: csv.DictWriter,
    *,
    link_status_counts: Counter,
    split_counts: Counter,
    label_counts: Counter,
    examples: list[dict],
    failure_examples: list[dict],
) -> None:
    if result["failed"]:
        link_status_counts["failed"] += 1
        if len(failure_examples) < MAX_FAILURE_EXAMPLES:
            row = result.get("row", {})
            failure_examples.append(
                {
                    "row_index": int(result["index"]),
                    "source_path": result.get("original_source_path", ""),
                    "destination": result.get("materialized_source_path", ""),
                    "split": row.get("split", ""),
                    "label": row.get("label", ""),
                    "error_type": result.get("error_type", ""),
                    "error": str(result.get("error", ""))[:500],
                }
            )
        return

    row = result["row"]
    status = result["status"]
    link_status_counts[status] += 1
    split_counts[row.get("split", "")] += 1
    label_counts[str(row.get("label", ""))] += 1
    writer.writerow({field: row.get(field, "") for field in writer.fieldnames or []})
    if len(examples) < 5:
        examples.append(
            {
                "original_source_path": result["original_source_path"],
                "materialized_source_path": result["materialized_source_path"],
                "status": status,
            }
        )


def _flush_ready(
    completed_by_index: dict[int, dict],
    next_to_write: int,
    writer: csv.DictWriter,
    *,
    link_status_counts: Counter,
    split_counts: Counter,
    label_counts: Counter,
    examples: list[dict],
    failure_examples: list[dict],
) -> int:
    while next_to_write in completed_by_index:
        result = completed_by_index.pop(next_to_write)
        _record_result(
            result,
            writer,
            link_status_counts=link_status_counts,
            split_counts=split_counts,
            label_counts=label_counts,
            examples=examples,
            failure_examples=failure_examples,
        )
        next_to_write += 1
    return next_to_write


def materialize_worktree(
    *,
    source_split: Path,
    source_data_dir: Path,
    worktree_root: Path,
    output_split: Path,
    summary_json: Path,
    link_mode: str,
    workers: int = 1,
    max_pending: Optional[int] = None,
) -> dict:
    source_split = resolve_path(source_split)
    source_data_dir = resolve_path(source_data_dir)
    worktree_root = resolve_path(worktree_root)
    output_split = resolve_path(output_split)
    summary_json = resolve_path(summary_json)

    if not source_split.exists():
        raise FileNotFoundError(f"Source split file not found: {source_split}")
    if not source_data_dir.exists():
        raise FileNotFoundError(f"Source data directory not found: {source_data_dir}")

    worker_count = max(1, int(workers))
    if max_pending is not None and max_pending < 1:
        raise ValueError("--max-pending must be at least 1")
    pending_limit = (
        min(MAX_PENDING_TASKS, max(1, worker_count * DEFAULT_PENDING_MULTIPLIER))
        if max_pending is None
        else min(int(max_pending), MAX_PENDING_TASKS)
    )
    link_status_counts = Counter()
    split_counts = Counter()
    label_counts = Counter()
    examples = []
    failure_examples = []
    planned_rows = 0
    next_to_write = 0
    completed_by_index: dict[int, dict] = {}
    output_fieldnames = ["source_path", "original_source_path", "label", "sample_index", "split"]

    def build_payload(index: int, row: dict) -> tuple[int, dict, str, str, str]:
        original_path = Path(row["source_path"])
        relative_path = safe_relative_path(original_path, source_data_dir)
        destination = worktree_root / relative_path
        return index, dict(row), str(original_path), str(destination), link_mode

    output_split.parent.mkdir(parents=True, exist_ok=True)
    with output_split.open("w", encoding="utf-8-sig", newline="") as output_handle:
        writer = csv.DictWriter(output_handle, fieldnames=output_fieldnames)
        writer.writeheader()
        if worker_count <= 1:
            for index, row in enumerate(iter_rows(source_split)):
                planned_rows += 1
                result = _materialize_one(build_payload(index, row))
                completed_by_index[index] = result
                next_to_write = _flush_ready(
                    completed_by_index,
                    next_to_write,
                    writer,
                    link_status_counts=link_status_counts,
                    split_counts=split_counts,
                    label_counts=label_counts,
                    examples=examples,
                    failure_examples=failure_examples,
                )
        else:
            pending = {}
            with ThreadPoolExecutor(max_workers=worker_count) as executor:
                for index, row in enumerate(iter_rows(source_split)):
                    planned_rows += 1
                    payload = build_payload(index, row)
                    future = executor.submit(_materialize_one, payload)
                    pending[future] = payload
                    if len(pending) >= pending_limit:
                        done, _remaining = wait(set(pending), return_when=FIRST_COMPLETED)
                        for future_done in done:
                            payload_done = pending.pop(future_done)
                            try:
                                result = future_done.result()
                            except Exception as exc:
                                result = _worker_exception_result(payload_done, exc)
                            completed_by_index[int(result["index"])] = result
                        next_to_write = _flush_ready(
                            completed_by_index,
                            next_to_write,
                            writer,
                            link_status_counts=link_status_counts,
                            split_counts=split_counts,
                            label_counts=label_counts,
                            examples=examples,
                            failure_examples=failure_examples,
                        )
                while pending:
                    done, _remaining = wait(set(pending), return_when=FIRST_COMPLETED)
                    for future_done in done:
                        payload_done = pending.pop(future_done)
                        try:
                            result = future_done.result()
                        except Exception as exc:
                            result = _worker_exception_result(payload_done, exc)
                        completed_by_index[int(result["index"])] = result
                    next_to_write = _flush_ready(
                        completed_by_index,
                        next_to_write,
                        writer,
                        link_status_counts=link_status_counts,
                        split_counts=split_counts,
                        label_counts=label_counts,
                        examples=examples,
                        failure_examples=failure_examples,
                    )

    summary = {
        "schema": "axon_random_20w_worktree_v1",
        "source_split": str(source_split),
        "source_data_dir": str(source_data_dir),
        "worktree_root": str(worktree_root),
        "output_split": str(output_split),
        "summary_json": str(summary_json),
        "link_mode": link_mode,
        "workers": worker_count,
        "max_pending_tasks": pending_limit if worker_count > 1 else 0,
        "planned_rows": planned_rows,
        "total_rows": planned_rows - int(link_status_counts["failed"]),
        "succeeded_rows": planned_rows - int(link_status_counts["failed"]),
        "failed_rows": int(link_status_counts["failed"]),
        "label_counts": dict(sorted(label_counts.items())),
        "split_counts": dict(sorted(split_counts.items())),
        "link_status_counts": dict(sorted(link_status_counts.items())),
        "examples": examples,
        "failure_examples": failure_examples,
        "ready_for_cache_recovery": int(link_status_counts["failed"]) == 0,
    }

    summary_json.parent.mkdir(parents=True, exist_ok=True)
    summary_json.write_text(json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8")
    return summary


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Materialize a 20w raw split into a hardlink worktree.")
    parser.add_argument("--source-split", type=Path, required=True)
    parser.add_argument("--source-data-dir", type=Path, default=DEFAULT_SOURCE_DATA_DIR)
    parser.add_argument("--worktree-root", type=Path, default=DEFAULT_WORKTREE_ROOT)
    parser.add_argument("--output-split", type=Path, default=DEFAULT_WORKTREE_SPLIT)
    parser.add_argument("--summary-json", type=Path, default=DEFAULT_SUMMARY_JSON)
    parser.add_argument("--link-mode", choices=["hardlink", "copy"], default="hardlink")
    parser.add_argument("--workers", type=int, default=32)
    parser.add_argument("--max-pending", type=int, default=None)
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = build_parser().parse_args(argv)
    summary = materialize_worktree(
        source_split=args.source_split,
        source_data_dir=args.source_data_dir,
        worktree_root=args.worktree_root,
        output_split=args.output_split,
        summary_json=args.summary_json,
        link_mode=args.link_mode,
        workers=max(1, int(args.workers)),
        max_pending=args.max_pending,
    )
    print(json.dumps(summary, indent=2, ensure_ascii=False))
    return 0 if summary["ready_for_cache_recovery"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
